[mypy]
python_version = 3.12
files = apps/api/app
ignore_missing_imports = True
show_error_codes = True
show_column_numbers = False
pretty = False
no_error_summary = True
exclude = (?x)(^apps/api/alembic/|/__pycache__/|/generated/)
