from enum import Enum


class TesseractFailureReason(str, Enum):
    BINARY_MISSING = "BINARY_MISSING"
    TRAINEDDATA_MISSING = "TRAINEDDATA_MISSING"
    TIMEOUT = "TIMEOUT"
    UNSUPPORTED_LANGUAGE = "UNSUPPORTED_LANGUAGE"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    INVALID_PATH = "INVALID_PATH"
    NATIVE_PIN_MISMATCH = "NATIVE_PIN_MISMATCH"
    MALFORMED_OUTPUT = "MALFORMED_OUTPUT"
    OUTPUT_LIMIT_EXCEEDED = "OUTPUT_LIMIT_EXCEEDED"
    TEMP_FILE_FAILURE = "TEMP_FILE_FAILURE"
    PROCESS_SPAWN_FAILURE = "PROCESS_SPAWN_FAILURE"
    UNEXPECTED_EXIT = "UNEXPECTED_EXIT"
    NETWORK_ATTEMPT = "NETWORK_ATTEMPT"
    UNVERIFIED_WINDOWS_BINARY = "UNVERIFIED_WINDOWS_BINARY"


AVAILABILITY_REASONS = {
    TesseractFailureReason.BINARY_MISSING,
    TesseractFailureReason.TRAINEDDATA_MISSING,
    TesseractFailureReason.UNSUPPORTED_LANGUAGE,
    TesseractFailureReason.CHECKSUM_MISMATCH,
    TesseractFailureReason.INVALID_PATH,
    TesseractFailureReason.NATIVE_PIN_MISMATCH,
    TesseractFailureReason.UNVERIFIED_WINDOWS_BINARY,
}


def public_failure_code(reason: TesseractFailureReason) -> str:
    if reason is TesseractFailureReason.TIMEOUT:
        return "OCR_TIMEOUT"
    if reason in AVAILABILITY_REASONS:
        return "OCR_ENGINE_UNAVAILABLE"
    return "OCR_FAILED"
