from typing import Protocol

from app.domain.types.parser import FileMetadata, FileParserResult, ParsedDocument, ParserExecutionPlan, ParserWorkerPayload, ResolvedTemporaryFile, TempFileAccessContext


class FileParserRunnerPort(Protocol):
    def run(self, payload: ParserWorkerPayload) -> FileParserResult: ...
class ParserPlanResolverPort(Protocol):
    def resolve(self, payload: ParserWorkerPayload, metadata: FileMetadata) -> ParserExecutionPlan: ...
class ParserPlanExecutorPort(Protocol):
    def execute(self, plan: ParserExecutionPlan, payload: ParserWorkerPayload) -> FileParserResult: ...
class ParserAdapter(Protocol):
    def parse(self, resolved_file: ResolvedTemporaryFile, metadata: FileMetadata) -> ParsedDocument: ...
class TemporaryFileResolverPort(Protocol):
    def resolve(self, file_ref: str, context: TempFileAccessContext) -> ResolvedTemporaryFile: ...
class TemporaryFileStorePort(Protocol):
    def delete(self, file_ref: str, context: TempFileAccessContext) -> None: ...
